package bbdd;
// Generated 14 feb 2023 10:49:52 by Hibernate Tools 6.1.3.Final

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.Set;

/**
 * Dia generated by hbm2java
 */
@SuppressWarnings("serial")
public class Dia implements java.io.Serializable {

	private Date dia;
	private int tempmax;
	private int tempmin;
	private String descripcion;
	private int humedad;
	private int viento;
	private String direccion;
	@SuppressWarnings("rawtypes")
	private Set horas = new HashSet(0);

	public Dia() {
	}

	public Dia(String dia, int tempmax, int tempmin, String descripcion, int humedad, int viento, String direccion) {
		SimpleDateFormat formateador = new SimpleDateFormat("yyyy-mm-dd");

		try {
			this.dia = new java.sql.Date(formateador.parse(dia).getTime());
		} catch (ParseException e) {
			e.printStackTrace();
		}
		this.tempmax = tempmax;
		this.tempmin = tempmin;
		this.descripcion = descripcion;
		this.humedad = humedad;
		this.viento = viento;
		this.direccion = direccion;
	}

	public Dia(Date dia, int tempmax, int tempmin, String descripcion, int humedad, int viento, String direccion,
			@SuppressWarnings("rawtypes") Set horas) {
		this.dia = dia;
		this.tempmax = tempmax;
		this.tempmin = tempmin;
		this.descripcion = descripcion;
		this.humedad = humedad;
		this.viento = viento;
		this.direccion = direccion;
		this.horas = horas;
	}

	public String getDiaString() {
		SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
		String diaString = formateador.format(dia);
		return diaString;
	}
	
	public Date getDia() {
		return this.dia;
	}

	public void setDia(Date dia) {
		this.dia = dia;
	}

	public int getTempmax() {
		return this.tempmax;
	}

	public void setTempmax(int tempmax) {
		this.tempmax = tempmax;
	}

	public int getTempmin() {
		return this.tempmin;
	}

	public void setTempmin(int tempmin) {
		this.tempmin = tempmin;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getHumedad() {
		return this.humedad;
	}

	public void setHumedad(int humedad) {
		this.humedad = humedad;
	}

	public int getViento() {
		return this.viento;
	}

	public void setViento(int viento) {
		this.viento = viento;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@SuppressWarnings("rawtypes")
	public Set getHoras() {
		return this.horas;
	}

	public void setHoras(@SuppressWarnings("rawtypes") Set horas) {
		this.horas = horas;
	}

}
