package bbdd;
// Generated 14 feb 2023 10:49:52 by Hibernate Tools 6.1.3.Final

import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/**
 * Hora generated by hbm2java
 */
@SuppressWarnings("serial")
public class Hora implements java.io.Serializable {

	private HoraId id;
	private Dia dia;
	private int temp;
	private String descripcion;
	private int presion;
	private int humedad;
	private int viento;
	private String direccion;

	private String stringHora;
	
	public Hora() {
	}

	public Hora(String hora,Dia dia, int temp, String descripcion, int presion, int humedad, int viento,
			String direccion) {
		
		stringHora = hora;
		
		SimpleDateFormat formateadorHora = new SimpleDateFormat("HH:mm");
		try {
			Time tiempo=new Time(formateadorHora.parse(hora).getTime());
			this.id=new HoraId(dia.getDia(), tiempo);
		} catch (ParseException e) {
			e.printStackTrace();
		}
		
		this.dia = dia;
		this.temp = temp;
		this.descripcion = descripcion;
		this.presion = presion;
		this.humedad = humedad;
		this.viento = viento;
		this.direccion = direccion;
	}

	public String getHora()	{
		return stringHora;
	}
	
	
	
	public HoraId getId() {
		return this.id;
	}

	public void setId(HoraId id) {
		this.id = id;
	}

	public Dia getDia() {
		return this.dia;
	}

	public void setDia(Dia dia) {
		this.dia = dia;
	}

	public int getTemp() {
		return this.temp;
	}

	public void setTemp(int temp) {
		this.temp = temp;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getPresion() {
		return this.presion;
	}

	public void setPresion(int presion) {
		this.presion = presion;
	}

	public int getHumedad() {
		return this.humedad;
	}

	public void setHumedad(int humedad) {
		this.humedad = humedad;
	}

	public int getViento() {
		return this.viento;
	}

	public void setViento(int viento) {
		this.viento = viento;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}
