package bbdd;
// Generated 14 feb 2023 10:49:52 by Hibernate Tools 6.1.3.Final

import java.sql.Date;
import java.sql.Time;

/**
 * HoraId generated by hbm2java
 */
@SuppressWarnings("serial")
public class HoraId implements java.io.Serializable {

	private Date dia;
	private Time hora;

	public HoraId() {
	}

	public HoraId(Date dia, Time hora) {
		this.dia = dia;
		this.hora = hora;
	}

	public Date getDia() {
		return this.dia;
	}

	public void setDia(Date dia) {
		this.dia = dia;
	}

	public Time getHora() {
		return this.hora;
	}

	public void setHora(Time hora) {
		this.hora = hora;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HoraId))
			return false;
		HoraId castOther = (HoraId) other;

		return ((this.getDia() == castOther.getDia())
				|| (this.getDia() != null && castOther.getDia() != null && this.getDia().equals(castOther.getDia())))
				&& ((this.getHora() == castOther.getHora()) || (this.getHora() != null && castOther.getHora() != null
						&& this.getHora().equals(castOther.getHora())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDia() == null ? 0 : this.getDia().hashCode());
		result = 37 * result + (getHora() == null ? 0 : this.getHora().hashCode());
		return result;
	}

}
